# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generated.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgenerated.proto\"W\n\rTicketRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12 \n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x0e.BingoCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"(\n\x0b\x42ingoTicket\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"6\n\x13\x42ingoTicketResponse\x12\x1f\n\tgenerated\x18\x01 \x03(\x0b\x32\x0c.BingoTicket*@\n\rBingoCategory\x12\x0b\n\x07UKBINGO\x10\x00\x12\x0b\n\x07USBINGO\x10\x01\x12\n\n\x06IMAGES\x10\x02\x12\t\n\x05WORDS\x10\x03\x32<\n\tGenerated\x12/\n\x07Tickets\x12\x0e.TicketRequest\x1a\x14.BingoTicketResponseb\x06proto3')

_BINGOCATEGORY = DESCRIPTOR.enum_types_by_name['BingoCategory']
BingoCategory = enum_type_wrapper.EnumTypeWrapper(_BINGOCATEGORY)
UKBINGO = 0
USBINGO = 1
IMAGES = 2
WORDS = 3


_TICKETREQUEST = DESCRIPTOR.message_types_by_name['TicketRequest']
_BINGOTICKET = DESCRIPTOR.message_types_by_name['BingoTicket']
_BINGOTICKETRESPONSE = DESCRIPTOR.message_types_by_name['BingoTicketResponse']
TicketRequest = _reflection.GeneratedProtocolMessageType('TicketRequest', (_message.Message,), {
  'DESCRIPTOR' : _TICKETREQUEST,
  '__module__' : 'generated_pb2'
  # @@protoc_insertion_point(class_scope:TicketRequest)
  })
_sym_db.RegisterMessage(TicketRequest)

BingoTicket = _reflection.GeneratedProtocolMessageType('BingoTicket', (_message.Message,), {
  'DESCRIPTOR' : _BINGOTICKET,
  '__module__' : 'generated_pb2'
  # @@protoc_insertion_point(class_scope:BingoTicket)
  })
_sym_db.RegisterMessage(BingoTicket)

BingoTicketResponse = _reflection.GeneratedProtocolMessageType('BingoTicketResponse', (_message.Message,), {
  'DESCRIPTOR' : _BINGOTICKETRESPONSE,
  '__module__' : 'generated_pb2'
  # @@protoc_insertion_point(class_scope:BingoTicketResponse)
  })
_sym_db.RegisterMessage(BingoTicketResponse)

_GENERATED = DESCRIPTOR.services_by_name['Generated']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BINGOCATEGORY._serialized_start=206
  _BINGOCATEGORY._serialized_end=270
  _TICKETREQUEST._serialized_start=19
  _TICKETREQUEST._serialized_end=106
  _BINGOTICKET._serialized_start=108
  _BINGOTICKET._serialized_end=148
  _BINGOTICKETRESPONSE._serialized_start=150
  _BINGOTICKETRESPONSE._serialized_end=204
  _GENERATED._serialized_start=272
  _GENERATED._serialized_end=332
# @@protoc_insertion_point(module_scope)
