# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bingo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ingo.proto\"7\n\rTicketRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\rno_of_tickets\x18\x02 \x01(\x05\"\x1d\n\x0cTicketCreate\x12\r\n\x05\x62oard\x18\x01 \x01(\t\"8\n\x0eTicketResponse\x12&\n\x0fticketgenerated\x18\x01 \x03(\x0b\x32\r.TicketCreate24\n\x07Tickets\x12)\n\x06Ticket\x12\x0e.TicketRequest\x1a\x0f.TicketResponseb\x06proto3')



_TICKETREQUEST = DESCRIPTOR.message_types_by_name['TicketRequest']
_TICKETCREATE = DESCRIPTOR.message_types_by_name['TicketCreate']
_TICKETRESPONSE = DESCRIPTOR.message_types_by_name['TicketResponse']
TicketRequest = _reflection.GeneratedProtocolMessageType('TicketRequest', (_message.Message,), {
  'DESCRIPTOR' : _TICKETREQUEST,
  '__module__' : 'bingo_pb2'
  # @@protoc_insertion_point(class_scope:TicketRequest)
  })
_sym_db.RegisterMessage(TicketRequest)

TicketCreate = _reflection.GeneratedProtocolMessageType('TicketCreate', (_message.Message,), {
  'DESCRIPTOR' : _TICKETCREATE,
  '__module__' : 'bingo_pb2'
  # @@protoc_insertion_point(class_scope:TicketCreate)
  })
_sym_db.RegisterMessage(TicketCreate)

TicketResponse = _reflection.GeneratedProtocolMessageType('TicketResponse', (_message.Message,), {
  'DESCRIPTOR' : _TICKETRESPONSE,
  '__module__' : 'bingo_pb2'
  # @@protoc_insertion_point(class_scope:TicketResponse)
  })
_sym_db.RegisterMessage(TicketResponse)

_TICKETS = DESCRIPTOR.services_by_name['Tickets']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TICKETREQUEST._serialized_start=15
  _TICKETREQUEST._serialized_end=70
  _TICKETCREATE._serialized_start=72
  _TICKETCREATE._serialized_end=101
  _TICKETRESPONSE._serialized_start=103
  _TICKETRESPONSE._serialized_end=159
  _TICKETS._serialized_start=161
  _TICKETS._serialized_end=213
# @@protoc_insertion_point(module_scope)
