# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generated_pb2 as generated__pb2


class GeneratedStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tickets = channel.unary_unary(
                '/Generated/Tickets',
                request_serializer=generated__pb2.TicketRequest.SerializeToString,
                response_deserializer=generated__pb2.BingoTicketResponse.FromString,
                )


class GeneratedServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Tickets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneratedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tickets': grpc.unary_unary_rpc_method_handler(
                    servicer.Tickets,
                    request_deserializer=generated__pb2.TicketRequest.FromString,
                    response_serializer=generated__pb2.BingoTicketResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Generated', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Generated(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Tickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Generated/Tickets',
            generated__pb2.TicketRequest.SerializeToString,
            generated__pb2.BingoTicketResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
