# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bingo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ingo.proto\"3\n\rTicketRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tmax_cards\x18\x02 \x01(\x05\"0\n\x10TicketGeneration\x12\r\n\x05\x63\x61rd1\x18\x01 \x01(\t\x12\r\n\x05\x63\x61rd2\x18\x02 \x01(\t\"=\n\x0eTicketResponse\x12+\n\x10generatedtickets\x18\x01 \x03(\x0b\x32\x11.TicketGeneration2:\n\x0bGenerations\x12+\n\x08Generate\x12\x0e.TicketRequest\x1a\x0f.TicketResponseb\x06proto3')



_TICKETREQUEST = DESCRIPTOR.message_types_by_name['TicketRequest']
_TICKETGENERATION = DESCRIPTOR.message_types_by_name['TicketGeneration']
_TICKETRESPONSE = DESCRIPTOR.message_types_by_name['TicketResponse']
TicketRequest = _reflection.GeneratedProtocolMessageType('TicketRequest', (_message.Message,), {
  'DESCRIPTOR' : _TICKETREQUEST,
  '__module__' : 'bingo_pb2'
  # @@protoc_insertion_point(class_scope:TicketRequest)
  })
_sym_db.RegisterMessage(TicketRequest)

TicketGeneration = _reflection.GeneratedProtocolMessageType('TicketGeneration', (_message.Message,), {
  'DESCRIPTOR' : _TICKETGENERATION,
  '__module__' : 'bingo_pb2'
  # @@protoc_insertion_point(class_scope:TicketGeneration)
  })
_sym_db.RegisterMessage(TicketGeneration)

TicketResponse = _reflection.GeneratedProtocolMessageType('TicketResponse', (_message.Message,), {
  'DESCRIPTOR' : _TICKETRESPONSE,
  '__module__' : 'bingo_pb2'
  # @@protoc_insertion_point(class_scope:TicketResponse)
  })
_sym_db.RegisterMessage(TicketResponse)

_GENERATIONS = DESCRIPTOR.services_by_name['Generations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TICKETREQUEST._serialized_start=15
  _TICKETREQUEST._serialized_end=66
  _TICKETGENERATION._serialized_start=68
  _TICKETGENERATION._serialized_end=116
  _TICKETRESPONSE._serialized_start=118
  _TICKETRESPONSE._serialized_end=179
  _GENERATIONS._serialized_start=181
  _GENERATIONS._serialized_end=239
# @@protoc_insertion_point(module_scope)
