# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bingo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ingo.proto\"T\n\rTicketRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1f\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\r.BookCategory\x12\x11\n\tmax_cards\x18\x03 \x01(\x05\"!\n\x10TicketGeneration\x12\r\n\x05title\x18\x01 \x01(\t\"=\n\x0eTicketResponse\x12+\n\x10generatedtickets\x18\x01 \x03(\x0b\x32\x11.TicketGeneration*?\n\x0c\x42ookCategory\x12\x0b\n\x07MYSTERY\x10\x00\x12\x13\n\x0fSCIENCE_FICTION\x10\x01\x12\r\n\tSELF_HELP\x10\x02\x32:\n\x0bGenerations\x12+\n\x08Generate\x12\x0e.TicketRequest\x1a\x0f.TicketResponseb\x06proto3')

_BOOKCATEGORY = DESCRIPTOR.enum_types_by_name['BookCategory']
BookCategory = enum_type_wrapper.EnumTypeWrapper(_BOOKCATEGORY)
MYSTERY = 0
SCIENCE_FICTION = 1
SELF_HELP = 2


_TICKETREQUEST = DESCRIPTOR.message_types_by_name['TicketRequest']
_TICKETGENERATION = DESCRIPTOR.message_types_by_name['TicketGeneration']
_TICKETRESPONSE = DESCRIPTOR.message_types_by_name['TicketResponse']
TicketRequest = _reflection.GeneratedProtocolMessageType('TicketRequest', (_message.Message,), {
  'DESCRIPTOR' : _TICKETREQUEST,
  '__module__' : 'bingo_pb2'
  # @@protoc_insertion_point(class_scope:TicketRequest)
  })
_sym_db.RegisterMessage(TicketRequest)

TicketGeneration = _reflection.GeneratedProtocolMessageType('TicketGeneration', (_message.Message,), {
  'DESCRIPTOR' : _TICKETGENERATION,
  '__module__' : 'bingo_pb2'
  # @@protoc_insertion_point(class_scope:TicketGeneration)
  })
_sym_db.RegisterMessage(TicketGeneration)

TicketResponse = _reflection.GeneratedProtocolMessageType('TicketResponse', (_message.Message,), {
  'DESCRIPTOR' : _TICKETRESPONSE,
  '__module__' : 'bingo_pb2'
  # @@protoc_insertion_point(class_scope:TicketResponse)
  })
_sym_db.RegisterMessage(TicketResponse)

_GENERATIONS = DESCRIPTOR.services_by_name['Generations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKCATEGORY._serialized_start=199
  _BOOKCATEGORY._serialized_end=262
  _TICKETREQUEST._serialized_start=15
  _TICKETREQUEST._serialized_end=99
  _TICKETGENERATION._serialized_start=101
  _TICKETGENERATION._serialized_end=134
  _TICKETRESPONSE._serialized_start=136
  _TICKETRESPONSE._serialized_end=197
  _GENERATIONS._serialized_start=264
  _GENERATIONS._serialized_end=322
# @@protoc_insertion_point(module_scope)
