# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bingo_pb2 as bingo__pb2


class TicketsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ticket = channel.unary_unary(
                '/Tickets/Ticket',
                request_serializer=bingo__pb2.TicketRequest.SerializeToString,
                response_deserializer=bingo__pb2.TicketResponse.FromString,
                )


class TicketsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ticket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ticket': grpc.unary_unary_rpc_method_handler(
                    servicer.Ticket,
                    request_deserializer=bingo__pb2.TicketRequest.FromString,
                    response_serializer=bingo__pb2.TicketResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Tickets', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tickets(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ticket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tickets/Ticket',
            bingo__pb2.TicketRequest.SerializeToString,
            bingo__pb2.TicketResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
